### ISSUE TITLE
Proguard ?

### ISSUE THREAD

**Issue by DevilGeek** [alipov/ews-android-api#21]
Does someone managed to get it working with proguard enable ?

**Comment by alipov** [comment]
What exactly doesn't work for you?
Please explain what you did and in case of error - describe what went wrong.

**Comment by tuckercr** [comment]
It's been a long time since I added EWS to my project, but I do have these lines in my proguard rules:
```
# For EWS and JavaDNS
-dontwarn java.applet.**
-dontwarn javax.servlet.**
-dontwarn javax.activation.**
-dontwarn org.ietf.jgss.**
-dontwarn org.apache.log.**
-dontwarn org.apache.log4j.**
-dontwarn org.apache.avalon.**
-dontwarn sun.net.spi.nameservice.**

**Comment by DevilGeek** [comment]
when i build my app in release with 
`minifyEnabled true`

the app crash 
`Caused by: java.lang.ClassNotFoundException: Didn't find class "android.org.apache.commons.logging.impl.LogFactoryImpl"`

**Comment by Domi04151309** [comment]
Add
```
-keep class android.org.apache.** { *; }
```
to your proguard rules

**Comment by dabarnard** [comment]
@Domi04151309 , the timing of your comment is impeccable as I myself was attempting to minify and shrink my app which uses this (great) library.

I can confirm that your suggestion solves the error mentioned by @DevilGeek 

Unfortunately, after this, there still seems to be an error introduced by the minify/shrink step:

`Caused by: android.org.apache.commons.logging.LogConfigurationException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference (Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference)`

The error seem seems to be referencing the LogFactoryImpl file:

`android.org.apache.commons.logging.impl.LogFactoryImpl`

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
                                                                                                    	at android.org.apache.commons.logging.impl.LogFactoryImpl.createLogFromClass(LogFactoryImpl.java:27)`

Did you experience the same issue on your end perhaps? Perhaps I am missing something obvious and I was hoping you, or anyone else in this thread, had some insight.

Thanks

**Comment by Domi04151309** [comment]
@dabarnard, I am encountering the same issue as you. Unfortunately, I have not been able to fix it yet. May I ask if the library works without minification for you? It does not work for me.

**Comment by dabarnard** [comment]
@Domi04151309 , I am in the same position as you. The library crashes on my end with minification enabled. I will continue to debug and let you know if I find a resolution - no luck so far unfortunately

**Comment by alipov** [comment]
@dabarnard @Domi04151309 

The following rules work for me:
```
# required in LogFactory#getLog
-keep class android.org.apache.commons.logging.impl.LogFactoryImpl { *; }

# required in LogFactoryImpl#discoverLogImplementation / LogFactoryImpl#createLogFromClass
-keep class android.org.apache.commons.logging.impl.Jdk14Logger { *; }

# required by EwsServiceXmlWriter
-keep class com.sun.xml.stream.ZephyrWriterFactory { *; }
# the below classes might be required as well
#-keep class com.sun.xml.stream.ZephyrParserFactory { *; }
#-keep class com.sun.xml.stream.events.ZephyrEventFactory { *; }
```

Please note that I don't have an active EWS endpoint to test against, so I couldn't test the whole flow.
Also, don't forget to remove the `-keep class android.org.apache.** { *; }` rule.

**Comment by dabarnard** [comment]
Hi @alipov, thanks so much for this. It did indeed solve the issue.

One note though, I needed to add the following additional line as well:

`-keep class android.org.apache.commons.logging.LogFactory { *; }`

Thanks again for your help in keeping this library active and working .
