### ISSUE TITLE
Email with CSS styling

### ISSUE THREAD

**Issue by aqibmapari** [alipov/ews-android-api#6]
I tried sending email body as an Html but doesnt quite seem to work.

I have tried the following
`message.setBody(new MessageBody(BodyType.HTML, _body));`

But still in outlook I can see the format is Plain text.
Even in gmail styles seem to be removed.
Almost all the html tags and inline css, tables etc. seems to be removed.
Can you please share some info on how to get this working.

**Comment by alipov** [comment]
This repo is just an Android wrapper around [ews-java-api](https://github.com/OfficeDev/ews-java-api) library.
Try to send this email using ews-java-api (from a PC). If you find problems there, open an issue on theirs repo. Otherwise, let me know if it works as you've expected with ews-java-api, but ews-android-api produces different results.
